[package]
name = "bench-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "3", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
serde = { version = "1", features = ["derive"] }
sysinfo = "0.37"
toml = "0.9"
