[package]
name = "hello-world-micro-web"
version = "0.1.0"
authors = ["zavakid <zava.kid@gmail.com>"]
edition = "2024"

[dependencies]
micro-web = "0.2"
tokio = { version = "1", features = ["full"] }
